#!/usr/bin/env bash

# === Basic vars =======================================================================
# directory of this script
d=$(dirname "$(readlink -f "$0")")

# -y or -n options to always pick yes/no at prompts
default_choice=""
if [[ $1 = -y ]]; then
    default_choice=true
elif [[ $1 = -n ]]; then
    default_choice=false
fi

config_home="${XDG_CONFIG_HOME:-$HOME/.config}"


# === Aux functions ====================================================================
# yes/no prompt
# $1: the prompt string
# $2: default value (optional) -- can be true or false
# returns: 0 if `yes` chosen; 1 if `no` chosen; if no default was given, will loop
# usage: `if yesno "wanna do the thing?" true; then
#             echo did the thing!
#         fi`
function yesno {
        qn=$1
        default=$2

        # set our default based on input
        if [ -z "$default" ]; then
            opts="[y/n]"
            default=""
        elif [ "$default" = true ]; then
            opts="[Y/n]"
            default="y"
        else
            opts="[y/N]"
            default="n"
        fi

        while true; do
            # read input
            read -p "$qn $opts " -n 1 -s -r input
            echo ${input}

            # if nothing entered and have a default, return it
            if [[ -z "$input" && ! -z "$default" ]]; then
                [ "$default" = "y" ] && return 0 || return 1
            fi

            # else if something entered, return if valid
            if [[ "$input" =~ ^[yYnN]$ ]]; then
                input=${input:-${default}}
                [[ "$input" =~ ^[yY]$ ]] && return 0 || return 1
            fi
        done
}

# symlink a dotfile, presenting a prompt (or doing a default behaviour) if there's a conflict
#
# note: if `$default_choice` is `true` or `false`, follow that instead of presenting a
# prompt in case of conflict.
# $1: name of the file (in this directory) to symlink
# $2: name of symlink, including directory -- defaults to ~/.$1
# returns: 0 if symlink was made for dotfile; else 1
function dotfile {
    # params
    dotfile_name="$1"
    link_name="${2:-$HOME/.$dotfile_name}"

    if [[ ! -f $d/$dotfile_name ]]; then
        echo "error in install.sh: can't find dotfile $dotfile_name"
        return 1
    fi

    # if `$link_name` exists, check if we should replace it with a new symlink
    if [[ -e "$link_name" || -L "$link_name" ]]; then
        if [[ "$default_choice" = false ]]; then
            echo "WARN: $link_name already exists, so did not make a link."
            return 1
        elif [[ "$default_choice" = "" ]] &&
             ! yesno "$link_name already exists -- replace it?" true; then
            return 1
        fi
        rm "$link_name"
    fi

    # make the symlink, including any needed dirs
    mkdir -p $(dirname "$link_name")
    ln -s "$d/$dotfile_name" "$link_name"
}


# === Symlinking dotfiles ==============================================================
dotfile bashrc
dotfile gitconfig "$config_home/git/config"
[[ $(tmux -V) =~ "tmux 3" ]] && dotfile tmux.conf "$config_home/tmux/tmux.conf" || dotfile tmux.conf
dotfile vimrc


# === Other bits =======================================================================
# make directories for vim swapfiles & backups
mkdir -p ~/.vim/backups
mkdir -p ~/.vim/swaps

# make directory for extra vim scripts
vim_personal_dir="$HOME/.vim/personal"
if [[ -e $vim_personal_dir ]]; then
    echo "vim personal dir already exists; skipping"
else
    [[ -d $d/vim ]] && ln -s $d/vim $vim_personal_dir
fi

# basic setup for vim plugin manager
vim_plug_dir="$HOME/.vim/autoload/plug.vim"
if [[ -e "$vim_plug_dir" ]]; then
    echo "plug.vim already exists in $vim_plug_dir; skipping"
else
    curl -fLo "$vim_plug_dir" --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

# setup tmux plugin manager
tpm_dir="$config_home/tmux/plugins/tpm"
if [[ -e "$tpm_dir" ]]; then
    echo "tpm already exists in $tpm_dir; skipping"
else
    git clone https://github.com/tmux-plugins/tpm "$tpm_dir"
fi

# basic rust setup (removes a warning, presumably generated by bash/cargo.bash)
rustup_dir="${XDG_DATA_HOME:-$HOME/.local/share}/rustup"
if [[ -e "$rustup_dir" ]]; then
    echo "rustup already exists in $rustup_dir; skipping"
elif [[ $default_choice = true ]] || yesno "do you want to install rust & cargo?"; then
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --no-modify-path
fi

# reminders for manual bits i've not automated yet
echo
echo DONE. remember to do these too:
echo \* run :PluginInstall in vim to install plugins
echo \* run \<prefix\>+I in tmux to install plugins
echo \* do any machine-specific setup in local.gitconfig, bash/local, vim/local etc.

