#!/usr/bin/env bash


# setup
source "$DOTFILES/bash/_utils.bash"


# utils
# minor checks that we're not about to splat over something.
# $1: (full) intended destination file path
pre-checks () {
    dest_dir="$(dirname "$1")"
    if [ ! -e "$dest_dir" ]; then
        mkdir -p "$dest_dir"
    elif [ ! -d "$dest_dir" ]; then
        >&2 error "A \`local\` file exists in the dotfiles dir, but it isn't a dir. Don't know what to do, so exiting."
        exit 1
    fi

    if [ -e "$1" ]; then
        >&2 error "Destination file "$(warn-col $1)" already exists. Don't know what to do, so exiting."
        exit 1
    fi
}

# generate from a stub file
# $1: stub file name, relative to this script's dir
# $2: (full) intended destination file path
from-stub-file () {
    local stub_file_name="$1"
    local destination_file_name="$2"

    pre-checks "$destination_file_name"

    cp "$stub_file_name" "$destination_file_name"
}

help-text () {
    echo "things to generate:"
    info-col "local-install   local-vim-plugins"
}


# handlers
local-install () {
    local dest="$DOTFILES/local/install"
    from-stub-file "stub.install" "$dest" || return 1

    chmod u+x "$dest"
}

local-vim-plugins () {
    from-stub-file "stub.plugins.vim" "$DOTFILES/local/plugins.vim" || return 1

    echo "$(info-col DONE). remember to also add this to your local/install:"
    echo 'symlink "$root/plugins.vim" "$HOME/.vim/local-plugins.vim" "vim local plugins"'
}


case "$1" in
    local-install)      local-install      "${@:2}" ;;
    local-vim-plugins)  local-vim-plugins  "${@:2}" ;;
    help|-h|"")         help-text ;;
    *)
        >&2 echo "unknown command $(warn-col "$1")."
        help-text
esac
