#!/usr/bin/env bash

source "$DOTFILES/bash/_utils.bash"

d="$HOME/src/bin/vim"

makefile_changed=0
pull_return_code=0
compile_needed=1
reconfig_needed=0

# get sources up-to-date
if [ ! -d "$d" ]; then
    # clone repo if not present
    if ! yesno "$(info "vim not yet cloned; clone now?")"; then
        echo did not clone.
        exit 0
    fi

    parent="$(dirname "$d")"
    mkdir -p "$parent"
    if [ "$?" != 0 ]; then
        >&2 error "failed to create directory $parent for vim clone; exiting"
        exit 1
    fi
    cd "$parent"

    git clone "https://github.com/vim/vim.git"
    pull_return_code="$?"
    cd "$d"
else
    # pull repo if present
    cd "$d"

    # check if makefile has been customised
    git diff --exit-code "$d/src/Makefile" >/dev/null 2>&1
    makefile_changed="$?"
    # not perfect logic as the unstash bumps the date, but good enough for our purposes?
    when_installed_changed="$(date -r src/Makefile +%s)"

    hash_before="$(git rev-parse HEAD)"

    # update
    git stash
    git pull
    pull_return_code="$?"
    git stash pop

    [ "$hash_before" == "$(git rev-parse HEAD)" ] && compile_needed=0
fi

if [ "$pull_return_code" != 0 ]; then
    >&2 error "git pull failed; not re-making"
    exit "$pull_return_code"
fi

# apply makefile customisation if needed
to_apply="$DOTFILES/local/other/vim.patch"
[ ! -f "$to_apply" ] && to_apply="$DOTFILES/other/vim.patch"
if [ -f "$to_apply" ]; then
    if [ "$makefile_changed" == 0 ]; then
        should_apply=1
    else
        when_dotfiles_changed="$(git -C "${to_apply%/other/vim.patch}" log -1 --pretty="format:%ct" "$to_apply")"
        if [ "$when_dotfiles_changed" -ge "$when_installed_changed" ]; then
            yesno "$(warn "dotfiles makefile newer than your modifications; overwrite from dotfiles?")" \
            && should_apply=1
        fi
    fi

    [ "$should_apply" == 1 ] \
    && git checkout @ -- src/Makefile \
    && git apply "$to_apply" \
    && reconfig_needed=1
fi

# rebuild if needed
if [ "$reconfig_needed" == 1 ]; then
    make reconfig && make
elif [ "$compile_needed" == 1 ]; then
    make
else
    info "already up-to-date; didn't rebuild"
fi